### ISSUE TITLE
不必要な unescape の発生

### ISSUE THREAD

**Issue by utgwkk** [nekowen/5000-trillion-yen-converter#2]
「5000兆円」など拡張機能が反応するワードと同じ DOM 要素に escape された HTML タグを埋め込んでおくと，
反応する文字列が変換される際に unescape されてしまいます．

# 例
https://sugarheart.utgw.net/5pyen.html

**Comment by nekowen** [comment]
@utgwkk 修正しました。ありがとうございます！
